POST http://localhost:3003/product/create
Content-Type: application/json

{
"name": "vestido vermelho tubinho",
"tags": "liso, BALADA"
}

###

GET http://localhost:3003/product/get
Content-Type: application/json

{
"name": "VESTIDO VERMELHO TUBINHO"
}