POST http://localhost:3003/user/signup
Content-Type: application/json

{
     "name":"Mariana Eduarda",
    "email": "eduarda9@gmail.com",
    "password": "123456"
}
### 

# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
  "email": "eduarda9@gmail.com",
  "password": "123456"
}
###
 @token = {{login.response.body.token}}
POST http://localhost:3003/post/create
Content-Type: application/json
Authorization: {{token}}

{
    "photo":"Praia",
     "description":"Maldivas",  
     "type": "NORMAL"
            
}

###
GET  http://localhost:3003/post/cb868fab-7db2-4f53-983e-2ba1d7b7870f
Content-Type: application/json
Authorization: {{token}}

 