POST  http://localhost:3003/user/signup
Content-Type: application/json

{
    "name":"Maria Eduarda",
    "email": "eduarda9@gmail.com",
    "password": "123456"
}
###
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
  "email": "eduarda9@gmail.com",
  "password": "123456"
}

###

 @token = {{login.response.body.token}}

GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: {{token}}

###

POST  http://localhost:3003/recipe
Content-Type: application/json
Authorization: {{token}}

{
    "title":"Cobertura de Bejinho",
    "description": "Cremoso",
    "preparation_mode": "Numa panela funda, acrescente o leite condensado, a margarina e o achocolatado ou 4 colheres de sopa de leite em pó."
}
###


GET http://localhost:3003/user/ea1b0938-446a-46fc-825c-c4dbae432b10
Content-Type: application/json
Authorization: {{token}}

###
GET http://localhost:3003/recipe/d2d24bd6-1f23-4817-a648-45af438e580b
Content-Type: application/json
Authorization: {{token}}