POST http://localhost:3003/client
Content-Type: application/json

{
     "id": 8
}

###
POST http://localhost:3003/buyer
Content-Type: application/json

{
     "name":"Erica Lima",
     "email": "ericalima@gmail.com",
     "cpf": "25462358885"
}

###
POST http://localhost:3003/payment
Content-Type: application/json

{
    "amount": "158",
    "type": "BOLETO",
    "card_holder_name": "Erica Lima",
    "card_number": "15987635815932456",
    "card_expiration_date": "02/2028",
    "card_cvv": "number",
    "client_id": "string",
    "buyer_id": "string",
    
        

}
###
GET http://localhost:3003/card
Content-Type: application/json

{        
   
    "amount": "158",
    "type": "BOLETO",
    "status": "PAGO OU A PAGAR",
    "card_holder_name": "string",
    "card_number": "string",
    "card_expiration_date": "mm/aaaa",
    "card_cvv": "number",
    "client_id": "string",
    "buyer_id": "string",
        

}
