
POST https://projeto-wirecard-back.herokuapp.com/client
Content-Type: application/json

{
     "id": 15
}

###
POST https://projeto-wirecard-back.herokuapp.com/buyer
Content-Type: application/json

{
     "name":"Gabi",
     "email": "gabi@gmail.com",
     "cpf": "25257894452"
}

###
POST https://projeto-wirecard-back.herokuapp.com/payment
Content-Type: application/json

{
    "amount": 7885,
    "type": "CARD",
    
    "card_cvv":"125",
     "card_expiration_date":"01/2056",
     "card_number":"1599877413211598",
     "card_holder_name":"Gabi",
    "client_id": "1",
    "buyer_id": "fc1b1e8d-75fc-4a7e-b851-d0211334658d"
}
###
GET https://projeto-wirecard-back.herokuapp.com/buyer/fc1b1e8d-75fc-4a7e-b851-d0211334658d

###
GET https://projeto-wirecard-back.herokuapp.com/payment/96dc0354-c5aa-45ba-a527-beb576cb174b
