POST http://localhost:3003/client
Content-Type: application/json

{
     "id": 8
}

###
POST http://localhost:3003/buyer
Content-Type: application/json

{
     "name":"Evelin Lima",
     "email": "evelinlima@gmail.com",
     "cpf": "98745963215"
}

###
POST http://localhost:3003/payment
Content-Type: application/json

{
    "amount": 2555,
    "type": "CARD",
    "status": "PAGO",
    "card_holder_name": "Evelin Lima",
    "card_number": "1598763581593246",
    "card_expiration_date": "02/2028",
    "card_cvv": "123",
    "client_id": "8",
    "buyer_id": "09137137-2122-45e6-922a-7607185e68fe"
}
###
GET http://localhost:3003/buyer/:id

###
GET http://localhost:3003/payment/:id
